/* Generated by Together */

package sparrow.elt.core.context;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.Map;

import sparrow.elt.core.dao.provider.DataProviderElement;
import sparrow.elt.core.exception.ProviderNotFoundException;
import sparrow.elt.core.exception.ResourceException;
import sparrow.elt.core.exception.ServiceUnavailableException;
import sparrow.elt.core.resource.Resource;
import sparrow.elt.core.services.PluggableService;
import sparrow.elt.core.transaction.SparrowTransactionManager;


/**
 *
 * <p>Title: </p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: </p>
 * @author not attributable
 * @version 1.0
 */
public interface SparrowContext {
  public Connection getDBConnection(String dsName) throws SQLException;

  public Resource getResource(String dsName) throws ResourceException;

  public Connection getTransactionEnabledDBConnection(String dsName) throws
      SQLException;

  public SparrowTransactionManager getTransactionManager();

  public PluggableService getService(String serviceName) throws
      ServiceUnavailableException;

  public String getContextParam(String paramName);

  public DataProviderElement getDataProviderElement(String dataProviderName) throws
      ProviderNotFoundException;

  public String getAppName();

  public String getProcessId();

  public String getAppDescription();

  public void setAttribute(String name,Object value);

  public Object getAttribute(String name);

  public Object getBean(String name);

  public Object getBean(String resourceName,String name);

  public Map getAttributes();
}
