//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.23 at 07:01:14 PM SGT 
//


package sparrow.etl.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NOTIFIERSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NOTIFIERSType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NOTIFIER" type="{}NOTIFIERType" maxOccurs="unbounded"/>
 *         &lt;element name="EVENTS" type="{}EVENTSType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NOTIFIERSType", propOrder = {
    "notifier",
    "events"
})
public class NOTIFIERSType {

    @XmlElement(name = "NOTIFIER", required = true)
    protected List<NOTIFIERType> notifier;
    @XmlElement(name = "EVENTS", required = true)
    protected EVENTSType events;

    /**
     * Gets the value of the notifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNOTIFIER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NOTIFIERType }
     * 
     * 
     */
    public List<NOTIFIERType> getNOTIFIER() {
        if (notifier == null) {
            notifier = new ArrayList<NOTIFIERType>();
        }
        return this.notifier;
    }

    /**
     * Gets the value of the events property.
     * 
     * @return
     *     possible object is
     *     {@link EVENTSType }
     *     
     */
    public EVENTSType getEVENTS() {
        return events;
    }

    /**
     * Sets the value of the events property.
     * 
     * @param value
     *     allowed object is
     *     {@link EVENTSType }
     *     
     */
    public void setEVENTS(EVENTSType value) {
        this.events = value;
    }

}
