//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.23 at 07:01:14 PM SGT 
//


package sparrow.etl.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sparrow.etl.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sparrow.etl.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DATAPROVIDERType }
     * 
     */
    public DATAPROVIDERType createDATAPROVIDERType() {
        return new DATAPROVIDERType();
    }

    /**
     * Create an instance of {@link LOADBALANCEType }
     * 
     */
    public LOADBALANCEType createLOADBALANCEType() {
        return new LOADBALANCEType();
    }

    /**
     * Create an instance of {@link MODULEType }
     * 
     */
    public MODULEType createMODULEType() {
        return new MODULEType();
    }

    /**
     * Create an instance of {@link HANDLERType }
     * 
     */
    public HANDLERType createHANDLERType() {
        return new HANDLERType();
    }

    /**
     * Create an instance of {@link SERVICEType }
     * 
     */
    public SERVICEType createSERVICEType() {
        return new SERVICEType();
    }

    /**
     * Create an instance of {@link SPARROWCONFIG }
     * 
     */
    public SPARROWCONFIG createSPARROWCONFIG() {
        return new SPARROWCONFIG();
    }

    /**
     * Create an instance of {@link SERVICESType }
     * 
     */
    public SERVICESType createSERVICESType() {
        return new SERVICESType();
    }

    /**
     * Create an instance of {@link RESOURCESType }
     * 
     */
    public RESOURCESType createRESOURCESType() {
        return new RESOURCESType();
    }

    /**
     * Create an instance of {@link RESOURCEType }
     * 
     */
    public RESOURCEType createRESOURCEType() {
        return new RESOURCEType();
    }

    /**
     * Create an instance of {@link HANDLEType }
     * 
     */
    public HANDLEType createHANDLEType() {
        return new HANDLEType();
    }

    /**
     * Create an instance of {@link ASSERTERype }
     * 
     */
    public ASSERTERype createASSERTERype() {
        return new ASSERTERype();
    }

    /**
     * Create an instance of {@link MODULEPARAMType }
     * 
     */
    public MODULEPARAMType createMODULEPARAMType() {
        return new MODULEPARAMType();
    }

    /**
     * Create an instance of {@link DATAEXTRACTORType }
     * 
     */
    public DATAEXTRACTORType createDATAEXTRACTORType() {
        return new DATAEXTRACTORType();
    }

    /**
     * Create an instance of {@link CYCLEDEPENDENCIESype }
     * 
     */
    public CYCLEDEPENDENCIESype createCYCLEDEPENDENCIESype() {
        return new CYCLEDEPENDENCIESype();
    }

    /**
     * Create an instance of {@link ERRORType }
     * 
     */
    public ERRORType createERRORType() {
        return new ERRORType();
    }

    /**
     * Create an instance of {@link LOOKUPType }
     * 
     */
    public LOOKUPType createLOOKUPType() {
        return new LOOKUPType();
    }

    /**
     * Create an instance of {@link DATATRANSFORMERType }
     * 
     */
    public DATATRANSFORMERType createDATATRANSFORMERType() {
        return new DATATRANSFORMERType();
    }

    /**
     * Create an instance of {@link EVENTType }
     * 
     */
    public EVENTType createEVENTType() {
        return new EVENTType();
    }

    /**
     * Create an instance of {@link EVENTSType }
     * 
     */
    public EVENTSType createEVENTSType() {
        return new EVENTSType();
    }

    /**
     * Create an instance of {@link DATALOOKUPType }
     * 
     */
    public DATALOOKUPType createDATALOOKUPType() {
        return new DATALOOKUPType();
    }

    /**
     * Create an instance of {@link DATAWRITERSType }
     * 
     */
    public DATAWRITERSType createDATAWRITERSType() {
        return new DATAWRITERSType();
    }

    /**
     * Create an instance of {@link WRITERType }
     * 
     */
    public WRITERType createWRITERType() {
        return new WRITERType();
    }

    /**
     * Create an instance of {@link PARAMType }
     * 
     */
    public PARAMType createPARAMType() {
        return new PARAMType();
    }

    /**
     * Create an instance of {@link EXCEPTIONHANDLERType }
     * 
     */
    public EXCEPTIONHANDLERType createEXCEPTIONHANDLERType() {
        return new EXCEPTIONHANDLERType();
    }

    /**
     * Create an instance of {@link NOTIFIERSType }
     * 
     */
    public NOTIFIERSType createNOTIFIERSType() {
        return new NOTIFIERSType();
    }

    /**
     * Create an instance of {@link DATAPROVIDERSType }
     * 
     */
    public DATAPROVIDERSType createDATAPROVIDERSType() {
        return new DATAPROVIDERSType();
    }

    /**
     * Create an instance of {@link NOTIFIERType }
     * 
     */
    public NOTIFIERType createNOTIFIERType() {
        return new NOTIFIERType();
    }

}
