//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vBeta
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2008.03.03 at 06:35:29 SGT
//

package sparrow.elt.jaxb;

/**
 * The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="DATAHANDLERType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="QUERY">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="RESULT-WRAP" default="disconnected" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="FETCH-SIZE" default="0" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="DB-SOURCE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PARAM" type="{}PARAMType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CLASS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TYPE" default="DB" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 */
public interface DATAHANDLERType {

  String getTYPE();

  void setTYPE(String value);

  java.util.List getPARAM();

  String getCLASS();

  void setCLASS(String value);

  sparrow.elt.jaxb.DATAHANDLERType.QUERYType getQUERY();

  void setQUERY(sparrow.elt.jaxb.DATAHANDLERType.QUERYType value);

  String getNAME();

  void setNAME(String value);

  /**
   * The following schema fragment specifies the expected content contained within this java content object.
   * <p>
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;attribute name="RESULT-WRAP" default="disconnected" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="FETCH-SIZE" default="0" type="{http://www.w3.org/2001/XMLSchema}int" />
   *       &lt;attribute name="DB-SOURCE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   *
   */
  public interface QUERYType {

    int getFETCHSIZE();

    void setFETCHSIZE(int value);

    String getDBSOURCE();

    void setDBSOURCE(String value);

    String getRESULTWRAP();

    void setRESULTWRAP(String value);

  }

}
