//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vBeta 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.06 at 11:48:43 SGT 
//


package sparrow.elt.jaxb;


/**
 * The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="MODULEType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PROCESS-ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LOAD-BALANCE" type="{}LOADBALANCEType" minOccurs="0"/>
 *         &lt;element name="CYCLE-DEPENDENCIES" type="{}CYCLEDEPENDENCIESype" minOccurs="0"/>
 *         &lt;element name="MODULE-PARAM" type="{}MODULE-PARAMType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface MODULEType {


    sparrow.elt.jaxb.MODULEPARAMType getMODULEPARAM();

    void setMODULEPARAM(sparrow.elt.jaxb.MODULEPARAMType value);

    String getPROCESSID();

    void setPROCESSID(String value);

    sparrow.elt.jaxb.LOADBALANCEType getLOADBALANCE();

    void setLOADBALANCE(sparrow.elt.jaxb.LOADBALANCEType value);

    String getNAME();

    void setNAME(String value);

    String getDESCRIPTION();

    void setDESCRIPTION(String value);

    sparrow.elt.jaxb.CYCLEDEPENDENCIESype getCYCLEDEPENDENCIES();

    void setCYCLEDEPENDENCIES(sparrow.elt.jaxb.CYCLEDEPENDENCIESype value);

}
