//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 07:57:22 AM SGT 
//


package sparrow.elt.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MODULE" type="{}MODULEType"/>
 *         &lt;element name="DATA-EXTRACTOR" type="{}DATAEXTRACTORType"/>
 *         &lt;element name="DATA-TRANSFORMER" type="{}DATATRANSFORMERType" minOccurs="0"/>
 *         &lt;element name="DATA-WRITERS" type="{}DATAWRITERSType"/>
 *         &lt;element name="RESOURCES" type="{}RESOURCESType" minOccurs="0"/>
 *         &lt;element name="SERVICES" type="{}SERVICESType" minOccurs="0"/>
 *         &lt;element name="DATA-PROVIDERS" type="{}DATAPROVIDERSType" minOccurs="0"/>
 *         &lt;element name="DATA-LOOKUP" type="{}DATALOOKUPType" minOccurs="0"/>
 *         &lt;element name="EXCEPTION-HANDLER" type="{}EXCEPTIONHANDLERType" minOccurs="0"/>
 *         &lt;element name="NOTIFIERS" type="{}NOTIFIERSType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "module",
    "dataextractor",
    "datatransformer",
    "datawriters",
    "resources",
    "services",
    "dataproviders",
    "datalookup",
    "exceptionhandler",
    "notifiers"
})
@XmlRootElement(name = "SPARROW-CONFIG")
public class SPARROWCONFIG {

    @XmlElement(name = "MODULE", required = true)
    protected MODULEType module;
    @XmlElement(name = "DATA-EXTRACTOR", required = true)
    protected DATAEXTRACTORType dataextractor;
    @XmlElement(name = "DATA-TRANSFORMER")
    protected DATATRANSFORMERType datatransformer;
    @XmlElement(name = "DATA-WRITERS", required = true)
    protected DATAWRITERSType datawriters;
    @XmlElement(name = "RESOURCES")
    protected RESOURCESType resources;
    @XmlElement(name = "SERVICES")
    protected SERVICESType services;
    @XmlElement(name = "DATA-PROVIDERS")
    protected DATAPROVIDERSType dataproviders;
    @XmlElement(name = "DATA-LOOKUP")
    protected DATALOOKUPType datalookup;
    @XmlElement(name = "EXCEPTION-HANDLER")
    protected EXCEPTIONHANDLERType exceptionhandler;
    @XmlElement(name = "NOTIFIERS")
    protected NOTIFIERSType notifiers;

    /**
     * Gets the value of the module property.
     * 
     * @return
     *     possible object is
     *     {@link MODULEType }
     *     
     */
    public MODULEType getMODULE() {
        return module;
    }

    /**
     * Sets the value of the module property.
     * 
     * @param value
     *     allowed object is
     *     {@link MODULEType }
     *     
     */
    public void setMODULE(MODULEType value) {
        this.module = value;
    }

    /**
     * Gets the value of the dataextractor property.
     * 
     * @return
     *     possible object is
     *     {@link DATAEXTRACTORType }
     *     
     */
    public DATAEXTRACTORType getDATAEXTRACTOR() {
        return dataextractor;
    }

    /**
     * Sets the value of the dataextractor property.
     * 
     * @param value
     *     allowed object is
     *     {@link DATAEXTRACTORType }
     *     
     */
    public void setDATAEXTRACTOR(DATAEXTRACTORType value) {
        this.dataextractor = value;
    }

    /**
     * Gets the value of the datatransformer property.
     * 
     * @return
     *     possible object is
     *     {@link DATATRANSFORMERType }
     *     
     */
    public DATATRANSFORMERType getDATATRANSFORMER() {
        return datatransformer;
    }

    /**
     * Sets the value of the datatransformer property.
     * 
     * @param value
     *     allowed object is
     *     {@link DATATRANSFORMERType }
     *     
     */
    public void setDATATRANSFORMER(DATATRANSFORMERType value) {
        this.datatransformer = value;
    }

    /**
     * Gets the value of the datawriters property.
     * 
     * @return
     *     possible object is
     *     {@link DATAWRITERSType }
     *     
     */
    public DATAWRITERSType getDATAWRITERS() {
        return datawriters;
    }

    /**
     * Sets the value of the datawriters property.
     * 
     * @param value
     *     allowed object is
     *     {@link DATAWRITERSType }
     *     
     */
    public void setDATAWRITERS(DATAWRITERSType value) {
        this.datawriters = value;
    }

    /**
     * Gets the value of the resources property.
     * 
     * @return
     *     possible object is
     *     {@link RESOURCESType }
     *     
     */
    public RESOURCESType getRESOURCES() {
        return resources;
    }

    /**
     * Sets the value of the resources property.
     * 
     * @param value
     *     allowed object is
     *     {@link RESOURCESType }
     *     
     */
    public void setRESOURCES(RESOURCESType value) {
        this.resources = value;
    }

    /**
     * Gets the value of the services property.
     * 
     * @return
     *     possible object is
     *     {@link SERVICESType }
     *     
     */
    public SERVICESType getSERVICES() {
        return services;
    }

    /**
     * Sets the value of the services property.
     * 
     * @param value
     *     allowed object is
     *     {@link SERVICESType }
     *     
     */
    public void setSERVICES(SERVICESType value) {
        this.services = value;
    }

    /**
     * Gets the value of the dataproviders property.
     * 
     * @return
     *     possible object is
     *     {@link DATAPROVIDERSType }
     *     
     */
    public DATAPROVIDERSType getDATAPROVIDERS() {
        return dataproviders;
    }

    /**
     * Sets the value of the dataproviders property.
     * 
     * @param value
     *     allowed object is
     *     {@link DATAPROVIDERSType }
     *     
     */
    public void setDATAPROVIDERS(DATAPROVIDERSType value) {
        this.dataproviders = value;
    }

    /**
     * Gets the value of the datalookup property.
     * 
     * @return
     *     possible object is
     *     {@link DATALOOKUPType }
     *     
     */
    public DATALOOKUPType getDATALOOKUP() {
        return datalookup;
    }

    /**
     * Sets the value of the datalookup property.
     * 
     * @param value
     *     allowed object is
     *     {@link DATALOOKUPType }
     *     
     */
    public void setDATALOOKUP(DATALOOKUPType value) {
        this.datalookup = value;
    }

    /**
     * Gets the value of the exceptionhandler property.
     * 
     * @return
     *     possible object is
     *     {@link EXCEPTIONHANDLERType }
     *     
     */
    public EXCEPTIONHANDLERType getEXCEPTIONHANDLER() {
        return exceptionhandler;
    }

    /**
     * Sets the value of the exceptionhandler property.
     * 
     * @param value
     *     allowed object is
     *     {@link EXCEPTIONHANDLERType }
     *     
     */
    public void setEXCEPTIONHANDLER(EXCEPTIONHANDLERType value) {
        this.exceptionhandler = value;
    }

    /**
     * Gets the value of the notifiers property.
     * 
     * @return
     *     possible object is
     *     {@link NOTIFIERSType }
     *     
     */
    public NOTIFIERSType getNOTIFIERS() {
        return notifiers;
    }

    /**
     * Sets the value of the notifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link NOTIFIERSType }
     *     
     */
    public void setNOTIFIERS(NOTIFIERSType value) {
        this.notifiers = value;
    }

}
