//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vBeta 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.08 at 03:21:16 SGT 
//


package sparrow.elt.jaxb;


/**
 * The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MODULE" type="{}MODULEType"/>
 *         &lt;element name="DATA-EXTRACTOR" type="{}DATAEXTRACTORType"/>
 *         &lt;element name="DATA-TRANSFORMER" type="{}DATATRANSFORMERType"/>
 *         &lt;element name="DATA-WRITERS" type="{}DATAWRITERSType"/>
 *         &lt;element name="RESOURCES" type="{}RESOURCESType" minOccurs="0"/>
 *         &lt;element name="SERVICES" type="{}SERVICESType" minOccurs="0"/>
 *         &lt;element name="DATA-PROVIDERS" type="{}DATAPROVIDERSType" minOccurs="0"/>
 *         &lt;element name="DATA-LOOKUP" type="{}DATALOOKUPType" minOccurs="0"/>
 *         &lt;element name="EXCEPTION-HANDLER" type="{}EXCEPTIONHANDLERType" minOccurs="0"/>
 *         &lt;element name="NOTIFIERS" type="{}NOTIFIERSType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface SPEARCONFIGType {


    sparrow.elt.jaxb.DATALOOKUPType getDATALOOKUP();

    void setDATALOOKUP(sparrow.elt.jaxb.DATALOOKUPType value);

    sparrow.elt.jaxb.SERVICESType getSERVICES();

    void setSERVICES(sparrow.elt.jaxb.SERVICESType value);

    sparrow.elt.jaxb.RESOURCESType getRESOURCES();

    void setRESOURCES(sparrow.elt.jaxb.RESOURCESType value);

    sparrow.elt.jaxb.DATAPROVIDERSType getDATAPROVIDERS();

    void setDATAPROVIDERS(sparrow.elt.jaxb.DATAPROVIDERSType value);

    sparrow.elt.jaxb.DATAWRITERSType getDATAWRITERS();

    void setDATAWRITERS(sparrow.elt.jaxb.DATAWRITERSType value);

    sparrow.elt.jaxb.EXCEPTIONHANDLERType getEXCEPTIONHANDLER();

    void setEXCEPTIONHANDLER(sparrow.elt.jaxb.EXCEPTIONHANDLERType value);

    sparrow.elt.jaxb.DATATRANSFORMERType getDATATRANSFORMER();

    void setDATATRANSFORMER(sparrow.elt.jaxb.DATATRANSFORMERType value);

    sparrow.elt.jaxb.DATAEXTRACTORType getDATAEXTRACTOR();

    void setDATAEXTRACTOR(sparrow.elt.jaxb.DATAEXTRACTORType value);

    sparrow.elt.jaxb.MODULEType getMODULE();

    void setMODULE(sparrow.elt.jaxb.MODULEType value);

    sparrow.elt.jaxb.NOTIFIERSType getNOTIFIERS();

    void setNOTIFIERS(sparrow.elt.jaxb.NOTIFIERSType value);

}
