//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.23 at 07:01:14 PM SGT 
//


package sparrow.etl.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DATALOOKUPType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DATALOOKUPType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LOOKUP" type="{}LOOKUPType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="LOAD-TYPE" type="{http://www.w3.org/2001/XMLSchema}string" default="AUTO" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DATALOOKUPType", propOrder = {
    "lookup"
})
public class DATALOOKUPType {

    @XmlElement(name = "LOOKUP", required = true)
    protected List<LOOKUPType> lookup;
    @XmlAttribute(name = "LOAD-TYPE")
    protected String loadtype;

    /**
     * Gets the value of the lookup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lookup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLOOKUP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LOOKUPType }
     * 
     * 
     */
    public List<LOOKUPType> getLOOKUP() {
        if (lookup == null) {
            lookup = new ArrayList<LOOKUPType>();
        }
        return this.lookup;
    }

    /**
     * Gets the value of the loadtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOADTYPE() {
        if (loadtype == null) {
            return "AUTO";
        } else {
            return loadtype;
        }
    }

    /**
     * Sets the value of the loadtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOADTYPE(String value) {
        this.loadtype = value;
    }

}
