//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.23 at 07:01:14 PM SGT 
//


package sparrow.etl.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DATAWRITERSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DATAWRITERSType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WRITER" type="{}WRITERType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ON-ERROR" type="{http://www.w3.org/2001/XMLSchema}string" default="ignore" />
 *       &lt;attribute name="THREAD-COUNT" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DATAWRITERSType", propOrder = {
    "writer"
})
public class DATAWRITERSType {

    @XmlElement(name = "WRITER", required = true)
    protected List<WRITERType> writer;
    @XmlAttribute(name = "ON-ERROR")
    protected String onerror;
    @XmlAttribute(name = "THREAD-COUNT")
    protected Integer threadcount;

    /**
     * Gets the value of the writer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the writer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWRITER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WRITERType }
     * 
     * 
     */
    public List<WRITERType> getWRITER() {
        if (writer == null) {
            writer = new ArrayList<WRITERType>();
        }
        return this.writer;
    }

    /**
     * Gets the value of the onerror property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getONERROR() {
        if (onerror == null) {
            return "ignore";
        } else {
            return onerror;
        }
    }

    /**
     * Sets the value of the onerror property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setONERROR(String value) {
        this.onerror = value;
    }

    /**
     * Gets the value of the threadcount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getTHREADCOUNT() {
        if (threadcount == null) {
            return  1;
        } else {
            return threadcount;
        }
    }

    /**
     * Sets the value of the threadcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTHREADCOUNT(Integer value) {
        this.threadcount = value;
    }

}
