/* Generated by Together */

package sparrow.etl.core.exception;


/**
 *
 * <p>Title: </p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: </p>
 * @author Saji Venugopalan
 * @version 1.0
 */
public class InitializationException
    extends SparrowRuntimeException {


  public InitializationException(String msg) {
    super(msg);
  }

  public InitializationException(String code, String message) {
    super(code, message);
  }

  public InitializationException(String msg, Exception original) {
    super(msg, original);
  }

  public InitializationException(Exception original) {
    super(original);
  }

}
