/* Generated by Together */

package sparrow.elt.core.exception;

import sparrow.elt.core.log.SparrowLogger;
import sparrow.elt.core.log.SparrowrLoggerFactory;

/**
 *
 * <p>Title: </p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: </p>
 * @author Saji Venugopalan
 * @version 1.0
 */
public class ConfigurationReadingException
    extends SparrowException {

  public ConfigurationReadingException() {
    super();
  }

  public ConfigurationReadingException(Exception e) {
    super(e);
  }

  public ConfigurationReadingException(String message, Exception e) {
    super(message, e);
  }

  public ConfigurationReadingException(String message) {
    super(message);
  }

}
