/* Generated by Together */

package sparrow.etl.core.services;

import sparrow.etl.core.config.SparrowServiceConfig;
import sparrow.etl.core.exception.ServiceInitializationException;
import sparrow.etl.core.exception.ServiceUnavailableException;
import sparrow.etl.core.monitor.AppObserver;
import sparrow.etl.core.monitor.CycleObserver;

public interface PluggableService
    extends AppObserver, CycleObserver {

  public Object getService() throws ServiceUnavailableException;

  public Object getService(Object serviceName) throws
      ServiceUnavailableException;

}
