//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vBeta 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.27 at 11:48:58 SGT 
//


package sparrow.elt.jaxb;


/**
 * The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="DATATRANSFORMERType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PARAM" type="{}PARAMType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CLASS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="THREAD-COUNT" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="POOL-SIZE" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="TYPE" default="DEFAULT" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface DATATRANSFORMERType {


    String getTYPE();

    void setTYPE(String value);

    java.util.List getPARAM();

    String getCLASS();

    void setCLASS(String value);

    int getPOOLSIZE();

    void setPOOLSIZE(int value);

    int getTHREADCOUNT();

    void setTHREADCOUNT(int value);

    String getNAME();

    void setNAME(String value);

}
