//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vBeta
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2007.12.11 at 03:02:58 SGT
//

package sparrow.elt.jaxb;

/**
 * The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="DATAWRITERSType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WRITER" type="{}WRITERType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ON-ERROR" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="THREAD-COUNT" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 */
public interface DATAWRITERSType {

  java.util.List getWRITER();

  String getONERROR();

  void setONERROR(String value);

  int getTHREADCOUNT();

  void setTHREADCOUNT(int value);

}
