//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vBeta
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2008.02.27 at 12:11:07 SGT
//

package sparrow.elt.jaxb;

/**
 * The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="QUERYType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DB-SOURCE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RESULT-WRAP" default="disconnected" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FETCH-SIZE" default="0" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 */
public interface QUERYType {

  int getFETCHSIZE();

  void setFETCHSIZE(int value);

  String getRESULTWRAP();

  void setRESULTWRAP(String value);

  String getDBSOURCE();

  void setDBSOURCE(String value);

}
