//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vBeta
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2008.05.26 at 09:25:09 SGT
//

package sparrow.elt.jaxb;

/**
 * The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="RESOURCEType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PARAM" type="{}PARAMType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CLASS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TYPE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LOAD-PRIORITY" default="0" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="UNLOAD-PRIORITY" default="0" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 */
public interface RESOURCEType {

  int getLOADPRIORITY();

  void setLOADPRIORITY(int value);

  String getTYPE();

  void setTYPE(String value);

  java.util.List getPARAM();

  String getCLASS();

  void setCLASS(String value);

  int getUNLOADPRIORITY();

  void setUNLOADPRIORITY(int value);

  String getNAME();

  void setNAME(String value);

}
